# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ v4, v3 ]
  pull_request:
    branches: [ v4, v3 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - name: Set up Visual Studio 2022
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 2022
      - run: cmake -B b -S . -G "Visual Studio 17 2022" -A Win32
      - run: cmake --build b
